#ifndef UUCONTROLLER_GLOBAL_H
#define UUCONTROLLER_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(CONTROLLER_EXPORT_SYMBOLS)
#define CONTROLLER_DLL_EXPORT Q_DECL_EXPORT
#else
#define CONTROLLER_DLL_EXPORT Q_DECL_IMPORT
#endif
#endif  // UUCONTROLLER_GLOBAL_H
